services:
  productdb:
    container_name: productdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  userdb:
    container_name: userdb
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SwN12345678
    restart: always
    ports:
      - "1433:1433" 
    volumes:
      - mssql_data:/data/db

  user.api:
    container_name: user.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5001
      - ConnectionStrings__Database=Server=userdb;Database=UserAPIIdentity;User Id=sa;Password=SwN12345678;Encrypt=False;TrustServerCertificate=True
    depends_on:
      - userdb
      
    ports:
      - "8081:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro


  product.api:
    container_name: product.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=mongodb://productdb:27017"
      - "DatabaseSettings__DatabaseName=ProductDb"
      - "DatabaseSettings__CollectionName=Product"
      - "DatabaseSettings__AuthorsCollection=Authors"
      - "DatabaseSettings__TypesCollection=Types" 
    depends_on:
      - productdb
    ports:
      - "8000:8080"


    
volumes:
  mongo_data:
  mssql_data:

