version: '3.8'

networks:
  usernet:

services:
  productdb:
    container_name: productdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db


  

  userdb:
    container_name: userdb
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SwN12345678*
    restart: always
    ports:
      - "6000:1433"
    volumes:
      - userdb-data:/var/opt/mssql
    networks:
      - usernet  

  user.api:
    container_name: user.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      # - "ConnectionStrings__Database=Server=userdb;Database=UserAAPIIdentity;User Id=sa;Password=SwN12345678*;TrustServerCertificate=True"
    depends_on:
      - userdb
    ports:
      - "6001:8080"
    # networks:
    #   - usernet
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro


  product.api:
    container_name: product.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "DatabaseSettings__ConnectionString=mongodb://productdb:27017"
      - "DatabaseSettings__DatabaseName=ProductDb"
      - "DatabaseSettings__CollectionName=Product"
      - "DatabaseSettings__AuthorsCollection=Authors"
      - "DatabaseSettings__TypesCollection=Types" 
    depends_on:
      - productdb
    ports:
      - "6002:8080"


    
  yarpapigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    depends_on:
      - product.api
      - user.api
    ports:
      - "6003:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro




volumes:
  mongo_data:
  # mssql_data:
  userdb-data:


