services:

  productdb:
    image: mongo 

  userdb:
    image: mcr.microsoft.com/mssql/server

  # distributedcache:
  #   image: redis


  product.api:
    image: ${DOCKER_REGISTRY-}productapi
    build:
      context: .
      dockerfile: Services/ProductManagement/Product.API/Dockerfile

  user.api:
    image: ${DOCKER_REGISTRY-}userapi
    build:
      context: .
      dockerfile: Services/UserManagement/User.API/Dockerfile

