version: '3.8'

services:

  productdb:
    image: mongo 

  userdb:
    image: mcr.microsoft.com/mssql/server
    # image: mcr.microsoft.com/mssql/server:2022-latest

  # distributedcache:
  #   image: redis


  product.api:
    image: ${DOCKER_REGISTRY-}productapi
    build:
      context: .
      dockerfile: Services/ProductManagement/Product.API/Dockerfile

  user.api:
    image: ${DOCKER_REGISTRY-}userapi
    build:
      context: .
      dockerfile: Services/UserManagement/User.API/Dockerfile
    depends_on:
      - userdb      

  # yarpapigateway:
  #   image: ${DOCKER_REGISTRY-}yarpapigateway
  #   build:
  #     context: .
  #     dockerfile: ApiGateway/YarpApiGateway/Dockerfile

    
  ocelot.gateway:
    image: ${DOCKER_REGISTRY-}ocelotgateway
    build:
      context: .
      dockerfile: ApiGateway/Ocelot.Gateway/Dockerfile

